remote_start:
  name: Remote Start
  description: Send to ThinQ device the remote start command.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: sensor
  fields:
    course:
      name: course
      description: Course (if not set will use current)
      required: false
      selector:
        text:

wake_up:
  name: WakeUp
  description: Send to ThinQ device the wakeup command.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: sensor

set_time:
  name: Set time
  description: Set time device.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: sensor
  fields:
    time_wanted:
      name: time
      description: Time (if not set will use Home-Assistant time)
      required: false
      selector:
        time:

set_fan_mode:
  name: Set fan mode
  description: Set fan operation for dehumidifier device.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: humidifier
  fields:
    fan_mode:
      name: Fan mode
      description: New value of fan mode.
      required: true
      example: "low"
      selector:
        text:

set_sleep_time:
  name: Set sleep time
  description: Set sleep time.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: climate
  fields:
    sleep_time:
      name: "Timeout"
      description: Timeout for sleep mode in minutes
      default: 60
      required: true
      selector:
        number:
          min: 0
          max: 720
          mode: box
          unit_of_measurement: minutes

set_stop_time:
  name: Set stop time
  description: Set stop time.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: climate
  fields:
    stop_time:
      name: "Timeout"
      description: Timeout for stop mode in minutes
      default: 60
      required: true
      selector:
        number:
          min: 0
          max: 1440
          mode: box
          unit_of_measurement: minutes
          
set_start_time:
  name: Set start time
  description: Set start time.
  target:
    entity:
      integration: smartthinq_sensors_custom
      domain: climate
  fields:
    start_time:
      name: "Timeout"
      description: Timeout for start mode in minutes
      default: 60
      required: true
      selector:
        number:
          min: 0
          max: 1440
          mode: box
          unit_of_measurement: minutes
